### PR TITLE
Create strings.xml

### PR DESCRIPTION
**Pull request by Primokorn**
French translation
Strings ended by "key" haven't been translated.

### CODE REVIEW

**Comment by vijai1996** [comment]
@Primokorn Thanks for your translation but can you please use the beta branch as your base? Beta contains a lot new strings.

**Comment by OffifialMITX** [comment]
Where can I find it?

**Comment by vijai1996** [comment]
@OffifialMITX you can switch between branches by clicking on branch in the code tab and choosing beta branch.
if you want to checkout beta branch ```git clone https://github.com/vijai1996/screenrecorder -b Beta`

**Comment by Primokorn** [comment]
No problem. I work on it right now.

**Pull request closed without merging**
